param([hashtable]$Context)

Write-Host "[frontend] Plugin ejecutado" -ForegroundColor Cyan
if ($null -ne $Context) {
  Write-Host ("Contexto: " + ($Context | ConvertTo-Json -Compress)) -ForegroundColor DarkGray
}

$rootOut = $Context.output_dir
if (-not $rootOut) { throw "[frontend] 'output_dir' no definido en Context" }
$outDir = Join-Path $rootOut 'client'
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

# --- package.json ---
$pkg = @{
  name = "mvp-client"
  private = $true
  version = "0.1.0"
  type = "module"
  scripts = @{ dev = "vite"; build = "vite build"; preview = "vite preview" }
  dependencies = @{ react = "^18.2.0"; "react-dom" = "^18.2.0" }
  devDependencies = @{ vite = "^5.0.0"; "@vitejs/plugin-react" = "^4.2.0" }
} | ConvertTo-Json -Depth 5
Set-Content -LiteralPath (Join-Path $outDir 'package.json') -Value $pkg -Encoding UTF8

# --- vite.config.js ---
$vite = @'
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: { host: "0.0.0.0", port: 5173 }
});
'@
Set-Content -LiteralPath (Join-Path $outDir 'vite.config.js') -Value $vite -Encoding UTF8

# --- index.html ---
$html = @'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MVP Client</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
  </html>
'@
Set-Content -LiteralPath (Join-Path $outDir 'index.html') -Value $html -Encoding UTF8

# --- src files ---
$srcDir = Join-Path $outDir 'src'
if (-not (Test-Path $srcDir)) { New-Item -ItemType Directory -Path $srcDir | Out-Null }

$main = @'
import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import "./index.css";

createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
'@
Set-Content -LiteralPath (Join-Path $srcDir 'main.jsx') -Value $main -Encoding UTF8

$app = @'
export default function App() {
  return (
    <main style={{ padding: 24 }}>
      <h1>MVP Client</h1>
      <p>Generated by MVP Console.</p>
    </main>
  );
}
'@
Set-Content -LiteralPath (Join-Path $srcDir 'App.jsx') -Value $app -Encoding UTF8

$css = "body{font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;margin:0;padding:0;background:#fafafa;color:#111}"
Set-Content -LiteralPath (Join-Path $srcDir 'index.css') -Value $css -Encoding UTF8

Write-Host "[frontend] Proyecto React+Vite generado en $outDir" -ForegroundColor Green
